name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Packer init
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: .

    - name: Packer formate
      uses: hashicorp/packer-github-actions@master
      with:
        command: fmt
        target: .
    # validate templates
    - name: Validate Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: ami.pkr.hcl
    - name: Build Artifact
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        target: ami.pkr.hcl        
